// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PullContactsHandlerFunc turns a function with the right signature into a pull contacts handler
type PullContactsHandlerFunc func(PullContactsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PullContactsHandlerFunc) Handle(params PullContactsParams) middleware.Responder {
	return fn(params)
}

// PullContactsHandler interface for that can handle valid pull contacts params
type PullContactsHandler interface {
	Handle(PullContactsParams) middleware.Responder
}

// NewPullContacts creates a new http.Handler for the pull contacts operation
func NewPullContacts(ctx *middleware.Context, handler PullContactsHandler) *PullContacts {
	return &PullContacts{Context: ctx, Handler: handler}
}

/* PullContacts swagger:route POST /pull-contacts pullContacts

publish pull-contact-source for contact-sources

*/
type PullContacts struct {
	Context *middleware.Context
	Handler PullContactsHandler
}

func (o *PullContacts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPullContactsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
