// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PullContactSourceHandlerFunc turns a function with the right signature into a pull contact source handler
type PullContactSourceHandlerFunc func(PullContactSourceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PullContactSourceHandlerFunc) Handle(params PullContactSourceParams) middleware.Responder {
	return fn(params)
}

// PullContactSourceHandler interface for that can handle valid pull contact source params
type PullContactSourceHandler interface {
	Handle(PullContactSourceParams) middleware.Responder
}

// NewPullContactSource creates a new http.Handler for the pull contact source operation
func NewPullContactSource(ctx *middleware.Context, handler PullContactSourceHandler) *PullContactSource {
	return &PullContactSource{Context: ctx, Handler: handler}
}

/* PullContactSource swagger:route POST /pull-contact-source pullContactSource

sync all contacts from a contact source

*/
type PullContactSource struct {
	Context *middleware.Context
	Handler PullContactSourceHandler
}

func (o *PullContactSource) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPullContactSourceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
