// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/simplycubed/contactkarma/contacts/gen-jobs/models"
)

// NewContactSourceCleanUpParams creates a new ContactSourceCleanUpParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContactSourceCleanUpParams() *ContactSourceCleanUpParams {
	return &ContactSourceCleanUpParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewContactSourceCleanUpParamsWithTimeout creates a new ContactSourceCleanUpParams object
// with the ability to set a timeout on a request.
func NewContactSourceCleanUpParamsWithTimeout(timeout time.Duration) *ContactSourceCleanUpParams {
	return &ContactSourceCleanUpParams{
		timeout: timeout,
	}
}

// NewContactSourceCleanUpParamsWithContext creates a new ContactSourceCleanUpParams object
// with the ability to set a context for a request.
func NewContactSourceCleanUpParamsWithContext(ctx context.Context) *ContactSourceCleanUpParams {
	return &ContactSourceCleanUpParams{
		Context: ctx,
	}
}

// NewContactSourceCleanUpParamsWithHTTPClient creates a new ContactSourceCleanUpParams object
// with the ability to set a custom HTTPClient for a request.
func NewContactSourceCleanUpParamsWithHTTPClient(client *http.Client) *ContactSourceCleanUpParams {
	return &ContactSourceCleanUpParams{
		HTTPClient: client,
	}
}

/* ContactSourceCleanUpParams contains all the parameters to send to the API endpoint
   for the contact source clean up operation.

   Typically these are written to a http.Request.
*/
type ContactSourceCleanUpParams struct {

	// Body.
	Body *models.PubsubMessage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the contact source clean up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContactSourceCleanUpParams) WithDefaults() *ContactSourceCleanUpParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the contact source clean up params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContactSourceCleanUpParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the contact source clean up params
func (o *ContactSourceCleanUpParams) WithTimeout(timeout time.Duration) *ContactSourceCleanUpParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contact source clean up params
func (o *ContactSourceCleanUpParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contact source clean up params
func (o *ContactSourceCleanUpParams) WithContext(ctx context.Context) *ContactSourceCleanUpParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contact source clean up params
func (o *ContactSourceCleanUpParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contact source clean up params
func (o *ContactSourceCleanUpParams) WithHTTPClient(client *http.Client) *ContactSourceCleanUpParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contact source clean up params
func (o *ContactSourceCleanUpParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the contact source clean up params
func (o *ContactSourceCleanUpParams) WithBody(body *models.PubsubMessage) *ContactSourceCleanUpParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the contact source clean up params
func (o *ContactSourceCleanUpParams) SetBody(body *models.PubsubMessage) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ContactSourceCleanUpParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
