// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/simplycubed/contactkarma/contacts/gen-jobs/models"
)

// ContactSourceCleanUpReader is a Reader for the ContactSourceCleanUp structure.
type ContactSourceCleanUpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContactSourceCleanUpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContactSourceCleanUpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewContactSourceCleanUpBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewContactSourceCleanUpOK creates a ContactSourceCleanUpOK with default headers values
func NewContactSourceCleanUpOK() *ContactSourceCleanUpOK {
	return &ContactSourceCleanUpOK{}
}

/* ContactSourceCleanUpOK describes a response with status code 200, with default header values.

Triggered
*/
type ContactSourceCleanUpOK struct {
	Payload *models.JobSuccess
}

func (o *ContactSourceCleanUpOK) Error() string {
	return fmt.Sprintf("[POST /contact-source-clean-up][%d] contactSourceCleanUpOK  %+v", 200, o.Payload)
}
func (o *ContactSourceCleanUpOK) GetPayload() *models.JobSuccess {
	return o.Payload
}

func (o *ContactSourceCleanUpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobSuccess)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContactSourceCleanUpBadRequest creates a ContactSourceCleanUpBadRequest with default headers values
func NewContactSourceCleanUpBadRequest() *ContactSourceCleanUpBadRequest {
	return &ContactSourceCleanUpBadRequest{}
}

/* ContactSourceCleanUpBadRequest describes a response with status code 400, with default header values.

Error
*/
type ContactSourceCleanUpBadRequest struct {
	Payload *models.JobError
}

func (o *ContactSourceCleanUpBadRequest) Error() string {
	return fmt.Sprintf("[POST /contact-source-clean-up][%d] contactSourceCleanUpBadRequest  %+v", 400, o.Payload)
}
func (o *ContactSourceCleanUpBadRequest) GetPayload() *models.JobError {
	return o.Payload
}

func (o *ContactSourceCleanUpBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
