// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	ContactSourceCleanUp(params *ContactSourceCleanUpParams, opts ...ClientOption) (*ContactSourceCleanUpOK, error)

	PullContactSource(params *PullContactSourceParams, opts ...ClientOption) (*PullContactSourceOK, error)

	PullContacts(params *PullContactsParams, opts ...ClientOption) (*PullContactsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ContactSourceCleanUp cleans up job after deleting a contact source
*/
func (a *Client) ContactSourceCleanUp(params *ContactSourceCleanUpParams, opts ...ClientOption) (*ContactSourceCleanUpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewContactSourceCleanUpParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "contact-source-clean-up",
		Method:             "POST",
		PathPattern:        "/contact-source-clean-up",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ContactSourceCleanUpReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ContactSourceCleanUpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for contact-source-clean-up: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PullContactSource syncs all contacts from a contact source
*/
func (a *Client) PullContactSource(params *PullContactSourceParams, opts ...ClientOption) (*PullContactSourceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPullContactSourceParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "pull-contact-source",
		Method:             "POST",
		PathPattern:        "/pull-contact-source",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PullContactSourceReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PullContactSourceOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for pull-contact-source: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PullContacts publishes pull contact source for contact sources
*/
func (a *Client) PullContacts(params *PullContactsParams, opts ...ClientOption) (*PullContactsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPullContactsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "pull-contacts",
		Method:             "POST",
		PathPattern:        "/pull-contacts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PullContactsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PullContactsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for pull-contacts: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
