// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/simplycubed/contactkarma/contacts/gen-jobs/models"
)

// PullContactsReader is a Reader for the PullContacts structure.
type PullContactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PullContactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPullContactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPullContactsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPullContactsOK creates a PullContactsOK with default headers values
func NewPullContactsOK() *PullContactsOK {
	return &PullContactsOK{}
}

/* PullContactsOK describes a response with status code 200, with default header values.

Triggered
*/
type PullContactsOK struct {
	Payload *models.JobSuccess
}

func (o *PullContactsOK) Error() string {
	return fmt.Sprintf("[POST /pull-contacts][%d] pullContactsOK  %+v", 200, o.Payload)
}
func (o *PullContactsOK) GetPayload() *models.JobSuccess {
	return o.Payload
}

func (o *PullContactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobSuccess)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPullContactsBadRequest creates a PullContactsBadRequest with default headers values
func NewPullContactsBadRequest() *PullContactsBadRequest {
	return &PullContactsBadRequest{}
}

/* PullContactsBadRequest describes a response with status code 400, with default header values.

Error
*/
type PullContactsBadRequest struct {
	Payload *models.JobError
}

func (o *PullContactsBadRequest) Error() string {
	return fmt.Sprintf("[POST /pull-contacts][%d] pullContactsBadRequest  %+v", 400, o.Payload)
}
func (o *PullContactsBadRequest) GetPayload() *models.JobError {
	return o.Payload
}

func (o *PullContactsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
