// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/simplycubed/contactkarma/contacts/gen-jobs/models"
)

// NewPullContactsParams creates a new PullContactsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPullContactsParams() *PullContactsParams {
	return &PullContactsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPullContactsParamsWithTimeout creates a new PullContactsParams object
// with the ability to set a timeout on a request.
func NewPullContactsParamsWithTimeout(timeout time.Duration) *PullContactsParams {
	return &PullContactsParams{
		timeout: timeout,
	}
}

// NewPullContactsParamsWithContext creates a new PullContactsParams object
// with the ability to set a context for a request.
func NewPullContactsParamsWithContext(ctx context.Context) *PullContactsParams {
	return &PullContactsParams{
		Context: ctx,
	}
}

// NewPullContactsParamsWithHTTPClient creates a new PullContactsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPullContactsParamsWithHTTPClient(client *http.Client) *PullContactsParams {
	return &PullContactsParams{
		HTTPClient: client,
	}
}

/* PullContactsParams contains all the parameters to send to the API endpoint
   for the pull contacts operation.

   Typically these are written to a http.Request.
*/
type PullContactsParams struct {

	// Body.
	Body *models.PubsubMessage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pull contacts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PullContactsParams) WithDefaults() *PullContactsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pull contacts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PullContactsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pull contacts params
func (o *PullContactsParams) WithTimeout(timeout time.Duration) *PullContactsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pull contacts params
func (o *PullContactsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pull contacts params
func (o *PullContactsParams) WithContext(ctx context.Context) *PullContactsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pull contacts params
func (o *PullContactsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pull contacts params
func (o *PullContactsParams) WithHTTPClient(client *http.Client) *PullContactsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pull contacts params
func (o *PullContactsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pull contacts params
func (o *PullContactsParams) WithBody(body *models.PubsubMessage) *PullContactsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pull contacts params
func (o *PullContactsParams) SetBody(body *models.PubsubMessage) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PullContactsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
