// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/simplycubed/contactkarma/contacts/gen-jobs/models"
)

// NewPullContactSourceParams creates a new PullContactSourceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPullContactSourceParams() *PullContactSourceParams {
	return &PullContactSourceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPullContactSourceParamsWithTimeout creates a new PullContactSourceParams object
// with the ability to set a timeout on a request.
func NewPullContactSourceParamsWithTimeout(timeout time.Duration) *PullContactSourceParams {
	return &PullContactSourceParams{
		timeout: timeout,
	}
}

// NewPullContactSourceParamsWithContext creates a new PullContactSourceParams object
// with the ability to set a context for a request.
func NewPullContactSourceParamsWithContext(ctx context.Context) *PullContactSourceParams {
	return &PullContactSourceParams{
		Context: ctx,
	}
}

// NewPullContactSourceParamsWithHTTPClient creates a new PullContactSourceParams object
// with the ability to set a custom HTTPClient for a request.
func NewPullContactSourceParamsWithHTTPClient(client *http.Client) *PullContactSourceParams {
	return &PullContactSourceParams{
		HTTPClient: client,
	}
}

/* PullContactSourceParams contains all the parameters to send to the API endpoint
   for the pull contact source operation.

   Typically these are written to a http.Request.
*/
type PullContactSourceParams struct {

	// Body.
	Body *models.PubsubMessage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pull contact source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PullContactSourceParams) WithDefaults() *PullContactSourceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pull contact source params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PullContactSourceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pull contact source params
func (o *PullContactSourceParams) WithTimeout(timeout time.Duration) *PullContactSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pull contact source params
func (o *PullContactSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pull contact source params
func (o *PullContactSourceParams) WithContext(ctx context.Context) *PullContactSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pull contact source params
func (o *PullContactSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pull contact source params
func (o *PullContactSourceParams) WithHTTPClient(client *http.Client) *PullContactSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pull contact source params
func (o *PullContactSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the pull contact source params
func (o *PullContactSourceParams) WithBody(body *models.PubsubMessage) *PullContactSourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the pull contact source params
func (o *PullContactSourceParams) SetBody(body *models.PubsubMessage) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PullContactSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
