// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobSuccess message
//
// swagger:model JobSuccess
type JobSuccess struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this job success
func (m *JobSuccess) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this job success based on context it is used
func (m *JobSuccess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobSuccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobSuccess) UnmarshalBinary(b []byte) error {
	var res JobSuccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
