// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PullContactsRequest PullContactsRequest
//
// swagger:model PullContactsRequest
type PullContactsRequest struct {

	// contact source Id
	ContactSourceID string `json:"contactSourceId,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this pull contacts request
func (m *PullContactsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pull contacts request based on context it is used
func (m *PullContactsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PullContactsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PullContactsRequest) UnmarshalBinary(b []byte) error {
	var res PullContactsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
