steps:
  - name: 'gcr.io/$PROJECT_ID/docker-compose'
    dir: 'contacts'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker-compose -f emulators/docker-compose.cloudbuild.yml -p contacts up -d',
      ]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
  - name: 'gcr.io/$PROJECT_ID/golang:latest'
    dir: 'contacts'
    entrypoint: go
    args: ['test', '-p', '1', '-cover', '-v', './...']
    env:
      - 'PROJECT_ROOT=github.com/simplycubed/contactkarma/contacts'
      - 'PORT=8080'
      - 'JOB_PORT=8090'
      - 'ENV=local'
      - 'FRONTEND_URL=https://app.contactkarma.dev'
      - 'FIREBASE_URL=http://contacts_emulator_1:4000?ns=emulatorui'
      - 'FIREBASE_AUTH_EMULATOR_HOST=contacts_emulator_1:9099'
      - 'FIRESTORE_PROJECT_ID=test'
      - 'ALLOWED_ORIGIN=*'
      - 'GOOGLE_CLOUD_PROJECT=test'
      - 'FIRESTORE_EMULATOR_HOST=contacts_emulator_1:9090'
      - 'GOOGLE_AUTH_CLIENT_ID=test.apps.googleusercontent.com'
      - 'GOOGLE_AUTH_CLIENT_SECRET=test-secret'
      - 'GOOGLE_AUTH_REDIRECT_URL=http://localhost:8080/auth/callback?provider=google'
      - PUBSUB_EMULATOR_HOST=contacts_emulator_1:8085
      - PUBSUB_PROJECT_ID=test
      - PULL_CONTACT_SOURCE_TOPIC=pull-contact-source
      - CONTACT_SOURCE_DELETED_TOPIC=contact-source-deleted
      - TYPESENSE_HOST=http://contacts_typesense_1:8108
      - TYPESENSE_API_KEY=test
  - name: 'gcr.io/$PROJECT_ID/golang:latest'
    dir: 'contacts'
    entrypoint: go
    args: ['build', './...']
    env: ['PROJECT_ROOT=github.com/simplycubed/contactkarma/contacts']
timeout: 900s
